spring:
  application.name: favorite-countries
  datasource:
    url: jdbc:h2:mem:countries
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8090

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui

logging:
  level:
    feign:
      client: DEBUG
    com.josalero.favoritecountry: DEBUG